# -*- coding: utf-8 -*-
"""sales-analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iBewAi9K6V9TsqEVipG6eqFpDfrT7L_j
"""

import pandas as pd
data =pd.read_csv("sample_sales_data.csv")
data

data.info()

data.describe()

data.isnull().sum()

data.head()

data.groupby("Product")["Total_Sales"].sum().sort_values(ascending=False)

data.groupby("Product")[["Quantity", "Total_Sales"]].sum()

data.groupby("Region")["Total_Sales"].sum().sort_values(ascending=False)

pd.pivot_table(data,
               values="Total_Sales",
               index="Region",
               columns="Product",
               aggfunc="sum")

data["Month"] = pd.to_datetime(data["Order_Date"]).dt.month
data.groupby("Month")["Total_Sales"].sum()

total_revenue = data["Total_Sales"].sum()
total_quantity = data["Quantity"].sum()
total_orders = data["Order_ID"].nunique()

print("Total Revenue:", total_revenue)
print("Total Quantity:", total_quantity)
print("Total Orders:", total_orders)

import pandas as pd
import matplotlib.pyplot as plt

# Load data
data = pd.read_csv("sample_sales_data.csv")

# Convert date
data["Order_Date"] = pd.to_datetime(data["Order_Date"])
data["Month"] = data["Order_Date"].dt.month

# Summaries
product_sales = (
    data.groupby("Product")["Total_Sales"]
    .sum()
    .sort_values(ascending=False)
)

region_sales = (
    data.groupby("Region")["Total_Sales"]
    .sum()
    .sort_values(ascending=False)
)

monthly_sales = (
    data.groupby("Month")["Total_Sales"]
    .sum()
    .sort_index()
)

# KPIs
total_revenue = data["Total_Sales"].sum()
total_orders = data["Order_ID"].nunique()
total_quantity = data["Quantity"].sum()

# Create Dashboard
plt.figure(figsize=(16,10))

plt.suptitle("Sales Performance Dashboard - 2024",
             fontsize=18,
             fontweight="bold")

# KPI Text
plt.figtext(0.5, 0.92,
            f"Total Revenue: {total_revenue:,.0f} | "
            f"Total Orders: {total_orders} | "
            f"Total Quantity Sold: {total_quantity}",
            ha="center",
            fontsize=11)

#  Sales by Product
plt.subplot(2,2,1)
product_sales.plot(kind="bar")
plt.title("Sales by Product")
plt.ylabel("Total Sales")
plt.xticks(rotation=45)

#  Sales by Region
plt.subplot(2,2,2)
region_sales.plot(kind="bar")
plt.title("Sales by Region")
plt.xticks(rotation=45)

#  Monthly Trend
plt.subplot(2,2,3)
monthly_sales.plot(marker="o")
plt.title("Monthly Sales Trend")
plt.xlabel("Month")
plt.ylabel("Total Sales")
plt.grid(alpha=0.3)

plt.tight_layout(rect=[0, 0, 1, 0.88])

# Save image
plt.savefig("dashboard.png", dpi=300, bbox_inches="tight")

plt.show()